name: Tests

on:
  push:
    tags:
      - '*'
    branches:
      - '**'
      - '!master'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Run Tests
      run: dotnet test
      shell: pwsh
